package gui;

import gui.tablemodel.RunnerInFinishedRaceTableModel;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.TableRowSorter;
import logic.obj.Race;
import logic.obj.RunnerInRace;
import logic.persistance.RepositoryImp;

public class FinishedRaceForm extends javax.swing.JDialog {
    private Race race;
    private List<RunnerInRace> runnersInRace;
    
    public FinishedRaceForm(java.awt.Frame parent, Race race) {
        super(parent, true);
        this.race = race;
        this.runnersInRace = RepositoryImp.getInstance().getRunnersInRace(this.race);
        initComponents();
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_buttons = new javax.swing.JPanel();
        btn_back = new javax.swing.JButton();
        pn_runners = new javax.swing.JPanel();
        scrpn_runners = new javax.swing.JScrollPane();
        tb_runners = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbl_name_text = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_location_text = new javax.swing.JLabel();
        lbl_location = new javax.swing.JLabel();
        lbl_date_text = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_max_text = new javax.swing.JLabel();
        lbl_max = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(FinishedRaceForm.class, "FinishedRaceForm.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(550, 320));

        pn_buttons.setLayout(new java.awt.GridLayout(1, 2, 18, 0));

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/back_x12.png"))); // NOI18N
        btn_back.setMnemonic('v');
        btn_back.setText(org.openide.util.NbBundle.getMessage(FinishedRaceForm.class, "FinishedRaceForm.btn_back.text")); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        pn_buttons.add(btn_back);

        pn_runners.setToolTipText(org.openide.util.NbBundle.getMessage(FinishedRaceForm.class, "FinishedRaceForm.pn_runners.toolTipText")); // NOI18N

        tb_runners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_runners.setEnabled(false);
        tb_runners.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrpn_runners.setViewportView(tb_runners);

        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 12, 0));

        lbl_name_text.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_name_text.setText(org.openide.util.NbBundle.getMessage(FinishedRaceForm.class, "FinishedRaceForm.lbl_name_text.text")); // NOI18N
        jPanel1.add(lbl_name_text);

        lbl_name.setText(org.openide.util.NbBundle.getMessage(FinishedRaceForm.class, "FinishedRaceForm.lbl_name.text")); // NOI18N
        jPanel1.add(lbl_name);

        lbl_location_text.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_location_text.setText(org.openide.util.NbBundle.getMessage(FinishedRaceForm.class, "FinishedRaceForm.lbl_location_text.text")); // NOI18N
        jPanel1.add(lbl_location_text);

        lbl_location.setText(org.openide.util.NbBundle.getMessage(FinishedRaceForm.class, "FinishedRaceForm.lbl_location.text")); // NOI18N
        jPanel1.add(lbl_location);

        lbl_date_text.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_date_text.setText(org.openide.util.NbBundle.getMessage(FinishedRaceForm.class, "FinishedRaceForm.lbl_date_text.text")); // NOI18N
        jPanel1.add(lbl_date_text);

        lbl_date.setText(org.openide.util.NbBundle.getMessage(FinishedRaceForm.class, "FinishedRaceForm.lbl_date.text")); // NOI18N
        jPanel1.add(lbl_date);

        lbl_max_text.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_max_text.setText(org.openide.util.NbBundle.getMessage(FinishedRaceForm.class, "FinishedRaceForm.lbl_max_text.text")); // NOI18N
        jPanel1.add(lbl_max_text);

        lbl_max.setText(org.openide.util.NbBundle.getMessage(FinishedRaceForm.class, "FinishedRaceForm.lbl_max.text")); // NOI18N
        jPanel1.add(lbl_max);

        javax.swing.GroupLayout pn_runnersLayout = new javax.swing.GroupLayout(pn_runners);
        pn_runners.setLayout(pn_runnersLayout);
        pn_runnersLayout.setHorizontalGroup(
            pn_runnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrpn_runners, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_runnersLayout.setVerticalGroup(
            pn_runnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_runnersLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrpn_runners, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pn_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pn_runners, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_runners, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void myInitComponents(){
        lbl_name.setText(this.race.getName());
        lbl_location.setText(this.race.getLocation());
        SimpleDateFormat format = new SimpleDateFormat("dd-mm-yyyy HH:mm:ss");
        lbl_date.setText(format.format(this.race.getDate()));
        lbl_max.setText(String.valueOf(this.runnersInRace.size()));
        updateTable();
    }
    
    private void updateTable(){
        Utils.lockCursor(this);
        RunnerInFinishedRaceTableModel runnerTableModel = new RunnerInFinishedRaceTableModel(runnersInRace);
        tb_runners.setModel(runnerTableModel);
        TableRowSorter<RunnerInFinishedRaceTableModel> sorter = new TableRowSorter<>(runnerTableModel);
        tb_runners.setRowSorter(sorter);
        /*
        ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>();
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
        */
        Utils.unlockCursor(this);
    }
    
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FinishedRaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FinishedRaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FinishedRaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FinishedRaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FinishedRaceForm dialog = new FinishedRaceForm(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_date_text;
    private javax.swing.JLabel lbl_location;
    private javax.swing.JLabel lbl_location_text;
    private javax.swing.JLabel lbl_max;
    private javax.swing.JLabel lbl_max_text;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_name_text;
    private javax.swing.JPanel pn_buttons;
    private javax.swing.JPanel pn_runners;
    private javax.swing.JScrollPane scrpn_runners;
    private javax.swing.JTable tb_runners;
    // End of variables declaration//GEN-END:variables
}
