package gui;

import static gui.Utils.messageConfirmationFinishRace;
import gui.component.JStopwatchListener;
import gui.component.RunnerTime;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import logic.obj.Race;
import logic.obj.RunnerInRace;
import logic.persistance.RepositoryImp;

public class RaceStart extends javax.swing.JDialog {
    private RaceManager parent;
    private Race race;
    private List<RunnerInRace> runnersInRace;
    private int lastRunnerPosition = 0;

    /**
     * Creates new form RaceStart
     */
    public RaceStart(java.awt.Frame parent, Race race, List<RunnerInRace> runnersInRace) {
        super(parent, true);
        this.parent = (RaceManager) parent;
        this.race = race;
        this.runnersInRace = runnersInRace;
        initComponents();
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_text = new javax.swing.JLabel();
        btn_jstopwatch = new gui.component.JStopwatch();
        pn_runners_info = new javax.swing.JPanel();
        lbl_finished_text = new javax.swing.JLabel();
        lbl_finished = new javax.swing.JLabel();
        lbl_left_text = new javax.swing.JLabel();
        lbl_left = new javax.swing.JLabel();
        pn_buttons = new javax.swing.JPanel();
        btn_finish = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(RaceStart.class, "RaceStart.title")); // NOI18N
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gui/img/flag_start_x64.png")).getImage());
        setMinimumSize(new java.awt.Dimension(550, 250));
        setResizable(false);

        lbl_text.setText(org.openide.util.NbBundle.getMessage(RaceStart.class, "RaceStart.lbl_text.text")); // NOI18N

        btn_jstopwatch.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        pn_runners_info.setLayout(new java.awt.GridLayout(2, 2, 10, 0));

        lbl_finished_text.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_finished_text.setText(org.openide.util.NbBundle.getMessage(RaceStart.class, "RaceStart.lbl_finished_text.text")); // NOI18N
        pn_runners_info.add(lbl_finished_text);

        lbl_finished.setText(org.openide.util.NbBundle.getMessage(RaceStart.class, "RaceStart.lbl_finished.text")); // NOI18N
        pn_runners_info.add(lbl_finished);

        lbl_left_text.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_left_text.setText(org.openide.util.NbBundle.getMessage(RaceStart.class, "RaceStart.lbl_left_text.text")); // NOI18N
        pn_runners_info.add(lbl_left_text);

        lbl_left.setText(org.openide.util.NbBundle.getMessage(RaceStart.class, "RaceStart.lbl_left.text")); // NOI18N
        pn_runners_info.add(lbl_left);

        pn_buttons.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btn_finish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/flag_finish_2_x16.png"))); // NOI18N
        btn_finish.setMnemonic('f');
        btn_finish.setText(org.openide.util.NbBundle.getMessage(RaceStart.class, "RaceStart.btn_finish.text")); // NOI18N
        btn_finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finishActionPerformed(evt);
            }
        });
        pn_buttons.add(btn_finish);

        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/remove_x12.png"))); // NOI18N
        btn_cancel.setMnemonic('c');
        btn_cancel.setText(org.openide.util.NbBundle.getMessage(RaceStart.class, "RaceStart.btn_cancel.text")); // NOI18N
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        pn_buttons.add(btn_cancel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(pn_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_jstopwatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_runners_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_jstopwatch, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_runners_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(pn_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finishActionPerformed
        if(messageConfirmationFinishRace(this) == JOptionPane.YES_OPTION){
            race.setFinished(true);
            RepositoryImp.getInstance().updateRace(race, race);
            for(RunnerInRace runnerInRace : runnersInRace)
                RepositoryImp.getInstance().updateRunnerInRace(runnerInRace, runnerInRace);
            parent.updateTable();
            this.dispose();
        }
    }//GEN-LAST:event_btn_finishActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        exit();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void myInitComponents(){
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e){
                exit();
            }
        });
        
        lbl_finished.setText("0");
        lbl_left.setText(String.valueOf(runnersInRace.size()));
        
        btn_jstopwatch.addJStopwatchListener(new JStopwatchListener() {
            @Override
            public void runnerGiven(RunnerTime runnerTime) {
                for(RunnerInRace runnerInRace : runnersInRace){
                    if(runnerInRace.getNumber() == runnerTime.getNumber() && runnerInRace.getPosition() == 0){
                        runnerInRace.setPosition(++lastRunnerPosition);
                        runnerInRace.setTime(runnerTime.getTime());
                        lbl_finished.setText(String.valueOf(Integer.parseInt(lbl_finished.getText()) +1));
                        lbl_left.setText(String.valueOf(Integer.parseInt(lbl_left.getText()) -1));
                        break;
                    }
                }
            }
        });
    }
    
    private void exit(){
        if(Utils.messageConfirmationCancelRace(this) == JOptionPane.YES_OPTION)
            this.dispose();
    }
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RaceStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RaceStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RaceStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RaceStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                RaceStart dialog = new RaceStart(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_finish;
    private gui.component.JStopwatch btn_jstopwatch;
    private javax.swing.JLabel lbl_finished;
    private javax.swing.JLabel lbl_finished_text;
    private javax.swing.JLabel lbl_left;
    private javax.swing.JLabel lbl_left_text;
    private javax.swing.JLabel lbl_text;
    private javax.swing.JPanel pn_buttons;
    private javax.swing.JPanel pn_runners_info;
    // End of variables declaration//GEN-END:variables
}
