package gui;

import gui.tablemodel.RunnerTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
import logic.obj.Runner;
import logic.persistance.RepositoryImp;

public class RunnerManager extends javax.swing.JFrame {
    private static RunnerManager instance = null;

    /**
     * Creates new form RunnerManager
     */
    private RunnerManager() {
        initComponents();
        myInitComponents();
    }
    
    public static RunnerManager getInstance(){
        if(instance == null)
            instance = new RunnerManager();
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrpn_table = new javax.swing.JScrollPane();
        tb_runners = new javax.swing.JTable();
        pn_buttons = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(RunnerManager.class, "MainWindow.btn_runner.text")); // NOI18N
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gui/img/runner_woman_x64.png")).getImage());
        setMinimumSize(new java.awt.Dimension(550, 300));

        scrpn_table.setPreferredSize(new java.awt.Dimension(350, 175));

        tb_runners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_runners.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrpn_table.setViewportView(tb_runners);

        pn_buttons.setLayout(new java.awt.GridLayout(1, 4, 18, 0));

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/add_x12.png"))); // NOI18N
        btn_add.setText(org.openide.util.NbBundle.getMessage(RunnerManager.class, "RunnerManager.btn_add.text")); // NOI18N
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        pn_buttons.add(btn_add);

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/edit_x12.png"))); // NOI18N
        btn_edit.setText(org.openide.util.NbBundle.getMessage(RunnerManager.class, "RunnerManager.btn_edit.text")); // NOI18N
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        pn_buttons.add(btn_edit);

        btn_remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/remove_x12.png"))); // NOI18N
        btn_remove.setText(org.openide.util.NbBundle.getMessage(RunnerManager.class, "RunnerManager.btn_remove.text")); // NOI18N
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });
        pn_buttons.add(btn_remove);

        jButton4.setText(org.openide.util.NbBundle.getMessage(RunnerManager.class, "RunnerManager.jButton4.text")); // NOI18N
        pn_buttons.add(jButton4);

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/back_x12.png"))); // NOI18N
        btn_back.setText(org.openide.util.NbBundle.getMessage(RunnerManager.class, "RunnerManager.btn_back.text")); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        pn_buttons.add(btn_back);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                    .addComponent(scrpn_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpn_table, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pn_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        Utils.allignAndShowFrame(new RunnerForm(this, null), this);
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        int selectedRow = tb_runners.getSelectedRow();
        if(selectedRow == -1){
            Utils.messageInformationSelectRunner(this);
            return;
        }
        Runner runner = RepositoryImp.getInstance().getRunner(tb_runners.convertColumnIndexToModel(selectedRow));
        Utils.allignAndShowFrame(new RunnerForm(this, runner), this);
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        int selectedRow = tb_runners.getSelectedRow();
        if(selectedRow == -1){
            Utils.messageInformationSelectRunner(this);
            return;
        }
        if(Utils.messageConfirmationRemoveRunner(this) == JOptionPane.YES_OPTION){
            Runner runner = RepositoryImp.getInstance().getRunners().get(tb_runners.convertColumnIndexToModel(selectedRow));
            RepositoryImp.getInstance().removeRunner(runner);
            updateTable();
        }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void myInitComponents() {  
        jButton4.setVisible(false);
        updateTable();
    }
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RunnerManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RunnerManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RunnerManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RunnerManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RunnerManager().setVisible(true);
//            }
//        });
//    }

    protected void updateTable(){
        Utils.lockCursor(this);
        RunnerTableModel runnerTableModel = new RunnerTableModel(RepositoryImp.getInstance().getRunners());
        tb_runners.setModel(runnerTableModel);
        TableRowSorter<RunnerTableModel> sorter = new TableRowSorter<>(runnerTableModel);
        tb_runners.setRowSorter(sorter);
        /*
        ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>();
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
        */
        Utils.unlockCursor(this);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel pn_buttons;
    private javax.swing.JScrollPane scrpn_table;
    private javax.swing.JTable tb_runners;
    // End of variables declaration//GEN-END:variables
}
